# This file was generated by GoReleaser. DO NOT EDIT.
cask "magelift" do
  version "0.0.0-dialproof.9"

  on_macos do
    on_arm do
      sha256 "84ae6586291554b92372f249ad562116aaeb05c1877ec8642703535545ab4830"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f6842fd4ec1e0bee0f764fa64f6173a07c35e4f19c1c75875e2d5705608a36f1"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "08ebe521dfb59e67ef5720df2ebb4ff8eb6a3fa375917adb8d537ca46f32c664"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b73e0e2de6976384119d66f7a28f76c8766aa528f573a3314d4515aa6d22fdce"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_linux_amd64.tar.gz"
    end
  end

  name "magelift"
  desc "Open-source Magento CLI for your AWS or GCP account"
  homepage "https://magelift.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "magelift"

  # No zap stanza required
end
