# This file was generated by GoReleaser. DO NOT EDIT.
cask "magelift" do
  version "0.0.0-dialproof.8"

  on_macos do
    on_arm do
      sha256 "d30bd8c22669e5a72d977e9ce27d6a4857411667e41e71034811c827cd3d4c59"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "250b926f4c979edc377c6095b1db283d6536a78fdfa03ec1eef0e76f40cef1f5"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "434b59499456182a0c934c5b37aed7220120cb2e1d9dfc0dae3ed09e91b81b5d"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "87b9d46065e8756a4da1b0e2f7a841cf7d813c6786d45a65908103c39c47ee9b"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_linux_amd64.tar.gz"
    end
  end

  name "magelift"
  desc "Open-source Magento CLI for your AWS or GCP account"
  homepage "https://magelift.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "magelift"

  # No zap stanza required
end
