# This file was generated by GoReleaser. DO NOT EDIT.
cask "magelift" do
  version "0.1.0-alpha.1-rc.15"

  on_macos do
    on_arm do
      sha256 "d1a41a3ea0daabbdb5c238d47203d4921a8086bbd79393c69ee4911daa4ff642"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c24f256dd068317b0d57195b227212ee8f712526e09536e18c170c509919bf9b"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c03eab3f02a071640b02115f220fadf2f6fcd3b9377ffc622adc9133b9f015f5"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "75b440a25eae278d0a7ff39fc0e18cf8e570b1e8e4d468cb6905aa4145c10bb3"
      url "https://github.com/magelift/magelift/releases/download/v#{version}/magelift_#{version}_linux_amd64.tar.gz"
    end
  end

  name "magelift"
  desc "Open-source Magento CLI for your AWS or GCP account"
  homepage "https://magelift.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "magelift"

  # No zap stanza required
end
